;;; modus-flexoki-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from modus-flexoki.el

(defvar modus-flexoki-take-over-modus-themes-mode nil
"Non-nil if Modus-Flexoki-Take-Over-Modus-Themes mode is enabled.
See the `modus-flexoki-take-over-modus-themes-mode' command
for a description of this minor mode.")
(custom-autoload 'modus-flexoki-take-over-modus-themes-mode "modus-flexoki" nil)
(autoload 'modus-flexoki-take-over-modus-themes-mode "modus-flexoki"
"When enabled, all Modus theme commands consider only Modus Flexoki themes.

Alternatively, use the dedicated commands `modus-flexoki-rotate',
`modus-flexoki-select', `modus-flexoki-load-random',
`modus-flexoki-load-random-dark',
`modus-flexoki-load-random-light',
`modus-flexoki-list-colors',
`modus-flexoki-list-colors-current'.
They are all designed to only consider Modus Flexoki themes.

This is a global minor mode.  If called interactively, toggle the
`Modus-Flexoki-Take-Over-Modus-Themes mode' mode.  If the prefix
argument is positive, enable the mode, and if it is zero or negative,
disable the mode.

If called from Lisp, toggle the mode if ARG is `toggle'.  Enable the
mode if ARG is nil, omitted, or is a positive number.  Disable the mode
if ARG is a negative number.

To check whether the minor mode is enabled in the current buffer,
evaluate `(default-value \\='modus-flexoki-take-over-modus-themes-mode)'.

The mode's hook is called both when the mode is enabled and when it is
disabled.

(fn &optional ARG)" t)
 (autoload 'modus-flexoki-rotate "modus-flexoki")
 (autoload 'modus-flexoki-select "modus-flexoki")
 (autoload 'modus-flexoki-load-random "modus-flexoki")
 (autoload 'modus-flexoki-load-random-dark "modus-flexoki")
 (autoload 'modus-flexoki-load-random-light "modus-flexoki")
 (autoload 'modus-flexoki-list-colors "modus-flexoki")
 (autoload 'modus-flexoki-list-colors-current "modus-flexoki")
(when load-file-name (let ((dir (file-name-directory load-file-name))) (unless (file-equal-p dir (expand-file-name "themes/" data-directory)) (add-to-list 'custom-theme-load-path dir))))
(register-definition-prefixes "modus-flexoki" '("modus-flexoki-"))


;;; Generated autoloads from modus-flexoki-dark-theme.el

(register-definition-prefixes "modus-flexoki-dark-theme" '("modus-flexoki-dark-palette"))


;;; Generated autoloads from modus-flexoki-light-theme.el

(register-definition-prefixes "modus-flexoki-light-theme" '("modus-flexoki-light-palette"))

;;; End of scraped data

(provide 'modus-flexoki-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; modus-flexoki-autoloads.el ends here
