;;; theme-loaddefs.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:



;;; Generated autoloads from modus-flexoki-dark-theme.el

(modus-themes-theme 'modus-flexoki-dark 'modus-flexoki
"Flexoki dark palette on modus-vivendi. " 'dark 'modus-vivendi-palette 'modus-flexoki-dark-palette 'modus-flexoki-dark-palette-overrides)


;;; Generated autoloads from modus-flexoki-light-theme.el

(modus-themes-theme 'modus-flexoki-light 'modus-flexoki
"Flexoki light palette on modus-operandi." 'light 'modus-operandi-palette 'modus-flexoki-light-palette 'modus-flexoki-light-palette-overrides)

;;; End of scraped data

(provide 'theme-loaddefs)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; theme-loaddefs.el ends here
